### ISSUE TITLE
I think I have an alternative?

### ISSUE THREAD

**Issue by ldd** [DSchau/gatsby-source-github#4]
Hey! I wrote something like this a while ago: https://www.npmjs.com/package/gatsby-source-github-api

I think it covers the usecase for this, right? 

Would you consider pointing your users over there? If not, no worries, I understand. But hopefully someone sees this in the issues for this repo and heads over there.

Cheers!

**Comment by DSchau** [comment]
I think these should generally both be deprecated! (In favor of gatsby-source-graphql)

But sure! PRs welcome

**Comment by ldd** [comment]
I've looked into it, and `gatsby-source-graphql` seems awesome.

I think that the best course of action was just mentioning my plugin here, in an issue, just in case someone is specifically looking for something like it.

So! I will not make any pull requests, and I will close down this issue.

Thanks!
